---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-ops
  namespace: system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nfs-client-provisioner-ops
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.8
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner
      tag: v3.1.0-k8s1.11
    nfs:
      path: /mnt/main/ops
      server: 10.0.0.11
      mountOptions:
        - tcp
        - intr
        - hard
        - noatime
        - nodiratime
        - rsize=32768
        - wsize=32768
    storageClass:
      # defaultClass: true
      name: "nfs-client-ops"
