apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jackett
    version: 4.0.0
  values:
    image:
      tag: v0.16.895-ls10
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - jackett.k8s.nickysemenza.com
    persistence:
      config:
        size: 1Gi
        storageClass: "nfs-client-ops"
    timezone: America/Los_Angeles
