apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    repository: https://billimek.com/billimek-charts/
    name: jellyfin
    version: 1.0.0
  values:
    timezone: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - jellyfin.k8s.nickysemenza.com
    nodeSelector:
      kubernetes.io/arch: amd64
      location: home
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-ops"
        accessMode: ReadWriteOnce
        size: 1Gi
        skipuninstall: false
      tvshows:
        enabled: false
        existingClaim: nfs-media
        accessMode: ReadWriteMany
        subPath: tv
      movies:
        enabled: false
        existingClaim: nfs-media
        accessMode: ReadWriteMany
        subPath: movies
      extraExistingClaimMounts:
        - name: nfs-media-mount
          mountPath: /srv/external-mount
          existingClaim: nfs-media
          accessMode: ReadWriteMany
