apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    repository: https://billimek.com/billimek-charts/
    name: plex
    version: 1.6.1
  values:
    advertiseIp: "http://10.0.0.198"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - plex.k8s.nickysemenza.com
    nodeSelector:
      kubernetes.io/arch: amd64
      location: home
    persistence:
      data:
        claimName: nfs-media
      config:
        size: 1Gi
        storageClass: "nfs-client-ops"

    timezone: America/Los_Angeles
  valuesFrom:
    - secretKeyRef:
        name: plex-claim-token
        namespace: media
        key: values.yaml
        optional: false
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 4.1.1
  values:
    # Prometheus Metrics
    exportarr:
      enabled: true
      url: "http://media-radarr.media.svc.cluster.local:7878"
      apikey: "f3f92f2793cd4563b76d346a9b6a8e54"
      port: 9708
      serviceMonitor:
        enabled: true
    timezone: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - radarr.k8s.nickysemenza.com
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-ops"
        accessMode: ReadWriteOnce
        size: 1Gi
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
      media:
        enabled: true
        existingClaim: nfs-media
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
