apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ombi
    version: 2.2.1
  values:
    timezone: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - ombi.k8s.nickysemenza.com
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-ops"
        accessMode: ReadWriteOnce
        size: 1Gi
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
    nodeSelector:
      kubernetes.io/arch: amd64
      location: home
