apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 4.1.1
  values:
    # Prometheus Metrics
    exportarr:
      enabled: false
      url: "http://sonarr.media.svc.cluster.local:7878"
      apikey: "todo"
      port: 9708
      serviceMonitor:
        enabled: true
    timezone: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - sonarr.k8s.nickysemenza.com
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-ops"
        accessMode: ReadWriteOnce
        size: 1Gi
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
      media:
        enabled: true
        existingClaim: nfs-media
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
