apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 1.6.1
  values:
    advertiseIp: "http://10.0.0.198"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - plex.k8s.nickysemenza.com
    nodeSelector:
      location: home
    persistence:
      data:
        claimName: nfs-media
      config:
        size: 1Gi
        storageClass: "nfs-client-ops"

    timezone: America/Los_Angeles
  valuesFrom:
    - secretKeyRef:
        name: plex-claim-token
        namespace: media
        key: values.yaml
        optional: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`10.0.0.198`)
      kind: Rule
      services:
        - name: media-plex-tcp
          port: 32400
  # tls:
  #   certResolver: le
  #   options: {}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`10.0.0.198`)
      kind: Rule
      services:
        - name: media-plex-tcp
          port: 32400
      # middlewares:
      #   - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-tcp
  namespace: media
spec:
  entryPoints:
    - plextcp
  routes:
    - match: Host(`10.0.0.198`)
      kind: Rule
      services:
        - name: media-media-plex-tcp-32400@kubernetes
          kind: TraefikService
