apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speedtest-prometheus
  namespace: exporters
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: speedtest-prometheus
    version: 2.0.0
  values:
    serviceMonitor:
      enabled: true
      interval: "60m"
    # TODO: make this DaemonSet so it runs on cloud and lan nodes
    replicaCount: 4
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: exporters
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: unifi-poller
    version: 2.0.1
  values:
    image:
      tag: stable
    config:
      influxdb:
        disable: true
      unifi:
        defaults:
          save_dpi: true
  valuesFrom:
    - secretKeyRef:
        name: unifi-poller-creds
        namespace: exporters
        key: values.yaml
        optional: false
