apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  chart:
    repository: https://halkeye.github.io/helm-charts
    name: whoami
    version: 0.3.2
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - whoami.k8s.nickysemenza.com
    replicaCount: 4
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
