apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: system
spec:
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured
    version: 2.2.0
  values:
    service:
      create: true
    image:
      repository: raspbernetes/kured
    configuration:
      period: "1h"
    tolerations:
      - key: "arm"
        operator: "Exists"
  valuesFrom:
    - secretKeyRef:
        name: kured-slack-webhook
        namespace: system
        key: values.yaml
        optional: false

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: system
spec:
  chart:
    repository: https://kubernetes.github.io/dashboard/
    name: kubernetes-dashboard
    version: 2.8.1
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - dashboard.k8s.nickysemenza.com
    # protocolHttp: true
    extraArgs:
      - --enable-skip-login
      - --enable-insecure-login
    metricsScraper:
      enabled: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-kubernetes-dashboard # k get serviceaccount | grep dash
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: system-kubernetes-dashboard
    namespace: system
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: system
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: node-feature-discovery
    version: 2.0.0
