apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 8.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    TZ: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - host: sonarr.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
        - host: tv.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: "local-path" # NFS and sqlite don't work well
        accessMode: ReadWriteOnce
        size: 1Gi
        skipuninstall: false
      media:
        enabled: true
        existingClaim: nfs-media-cantaloupe
        skipuninstall: false
