apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tautulli
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    TZ: America/Los_Angeles
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - host: tautulli.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-cantaloupe-ops"
        accessMode: ReadWriteOnce
        size: 1Gi
        ## Do not delete the pvc upon helm uninstall
        skipuninstall: false
      # media:
      #   enabled: true
      #   existingClaim: nfs-media-cantaloupe
      #   ## Do not delete the pvc upon helm uninstall
      #   skipuninstall: false
