apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vmware
  namespace: exporters
spec:
  chart:
    repository: https://kremers.github.io/
    name: vmware-exporter
    version: 2.0.0
  valuesFrom:
    - secretKeyRef:
        name: vmware-creds
        namespace: exporters
        key: values.yaml
        optional: false
  values:
    image:
      tag: latest
    vsphere:
      host: 10.0.0.14
      ignoressl: true
    service:
      enabled: true
    nodeSelector:
      location: cloud
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - vmware-metrics.k8s.nickysemenza.com
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "vmware"
  namespace: exporters
spec:
  selector:
    matchLabels:
      app: vmware-exporter
  endpoints:
    - port: http
