apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  releaseName: mosquitto
  values:
    nodeSelector:
      location: home
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    ingress:
      enabled: true
      # annotations:
      # traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - host: hass.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
        - host: hass.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client-cantaloupe-ops"
        accessMode: ReadWriteOnce
        size: 4Gi

    prometheus:
      serviceMonitor:
        enabled: true
        bearerTokenSecret:
          key: token
          name: prometheus-hass

    addons:
      codeserver:
        enabled: true
        volumeMounts:
          - name: config
            mountPath: /data/config
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
          hosts:
            - host: hass-config.k8s.nickysemenza.com
              paths:
                - path: /
                  pathType: Prefix

    nodeSelector:
      location: home
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    nodeSelector:
      location: home
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - host: node-red.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: "nfs-client-cantaloupe-ops"
        size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    TZ: America/Los_Angeles
    config:
      additionalVolumeMounts:
        - name: usb
          mountPath: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D90913-if00

      additionalVolumes:
        - name: usb
          hostPath:
            path: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D90913-if00
      # These will be applied ONLY on first run
      homeassistant: true
      permit_join: true
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://mosquitto.home.svc.cluster.local"
      serial:
        port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D90913-if00
      # Both of these need to be enabled for the webui
      frontend:
        port: 8080
      experimental:
        new_api: true
      devices:
        "0x00158d000421e252":
          friendly_name: "e252"
        "0x00158d000421e213":
          friendly_name: "e213"
        "0x00158d000421e143":
          friendly_name: "e143"
        "0x00158d000421e250":
          friendly_name: "e250"

    persistence:
      data:
        enabled: true
        storageClass: "nfs-client-cantaloupe-ops"
        size: 100Mi
        accessMode: ReadWriteOnce

    nodeSelector:
      kubernetes.io/hostname: plum
    tolerations:
      - key: "arm"
        operator: "Exists"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - host: zigbee.k8s.nickysemenza.com
          paths:
            - path: /
              pathType: Prefix
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homebridge
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    config:
      plugins: ["homebridge-tplink-smarthome"]
    service:
      httpPort: 6569
    hostNetwork: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - homebridge.k8s.nickysemenza.com
    persistence:
      enabled: true
      storageClass: "nfs-client-cantaloupe-ops"
