apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: logs
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mongodb
      version: 10.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux
      interval: 1m
  values:
    architecture: "replicaset"
    useStatefulSet: true
    replicaCount: 1
    auth:
      enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - name: mongodb.k8s.nickysemenza.com
          path: /
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-exporter
  namespace: logs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-mongodb-exporter
      version: 2.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux
      interval: 1m
  values:
    mongodb:
      uri: "mongodb://mongodb-headless.logs.svc.cluster.local:27017"
    serviceMonitor:
      enabled: true
