apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: media
  name: mnt-nfs-media-cantaloupe
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=3
  claimRef:
    namespace: media
    name: nfs-media-cantaloupe
  nfs:
    path: /volume1/media
    server: cantaloupe.lan.nickysemenza.com
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - strawberry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nfs-media-cantaloupe
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: mnt-nfs-media-cantaloupe
