apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 9.18.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux
      interval: 1m
  values:
    additionalArguments:
      - "--log.level=DEBUG"
      # - "--tracing.jaeger.samplingServerURL=http://monitoring-jaeger-agent.monitoring.svc.cluster.local:5778/sampling"
      # - "--tracing.jaeger.localAgentHostPort=monitoring-jaeger-agent.monitoring.svc.cluster.local:6831"
      # - "--tracing.jaeger.collector.endpoint=http://monitoring-jaeger-collector.monitoring.svc.cluster.local:14268/api/traces?format=jaeger.thrift"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--serversTransport.insecureSkipVerify=true" # for k8s dash
      - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entrypoints.fooudp.address=:8191/udp"

    service:
      spec:
        externalTrafficPolicy: Local # https://github.com/rancher/k3s/issues/1652 need this for X-Real-Ip?

    nodeSelector:
      location: home
    ports:
      fooudp:
        port: 8191
        # hostPort: 8443
        expose: true
        exposedPort: 8191
        protocol: UDP
      # plextcp:
      #   port: 32400
      #   # hostPort: 8443
      #   expose: true
      #   exposedPort: 32400
      #   protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.k8s.nickysemenza.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cf-access-auth
  namespace: system
spec:
  forwardAuth:
    address: "http://traefik-auth-cloudflare.default.svc.cluster.local/auth/c23fdb6f024e88908a4a8fabee5c821db65f7017ba4ae9996279d893f7e79405"
