apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: logs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://packages.timber.io/helm/latest
      chart: vector-agent
      version: 0.12.2
      sourceRef:
        kind: HelmRepository
        name: timberio
        namespace: flux
      interval: 5m
  values:
    # The Vector Kubernetes integration automatically defines a
    # kubernetes_logs source that is made available to you.
    # You do not need to define a log source.
    sinks:
      # Adjust as necessary. By default we use the console sink
      # to print all data. This allows you to see Vector working.
      # /docs/reference/sinks/
      stdout:
        type: console
        inputs: ["kubernetes_logs"]
        target: "stdout"
        encoding: "json"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: logs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://packages.timber.io/helm/nightly
      chart: vector-aggregator
      version: 0.13.0-nightly-2021-04-18
      sourceRef:
        kind: HelmRepository
        name: timberio-nightly
        namespace: flux
      interval: 5m
  values:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      # Additional ports to expose.
      ports:
        - name: syslog1
          port: 9020
          protocol: TCP
        # - name: syslog2
        #   port: 9021
        #   protocol: UDP
    sources:
      syslog_1:
        type: syslog
        address: 0.0.0.0:9020
        mode: tcp
      # syslog_2:
      #   type: syslog
      #   address: 0.0.0.0:9021
      #   mode: udp
    sinks:
      my_sink_id:
        type: console
        inputs:
          - syslog_1
          - syslog_2
          - prefix-*
        target: stdout
        encoding:
          codec: json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator-2
  namespace: logs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://packages.timber.io/helm/nightly
      chart: vector-aggregator
      version: 0.13.0-nightly-2021-04-18
      sourceRef:
        kind: HelmRepository
        name: timberio-nightly
        namespace: flux
      interval: 5m
  values:
    service:
      type: NodePort
      # externalTrafficPolicy: Local
      # Additional ports to expose.
      ports:
        # - name: syslog1
        #   port: 9020
        #   protocol: TCP
        - name: syslog2
          port: 9021
          protocol: UDP
          nodePort: 30007
    sources:
      # syslog_1:
      #   type: syslog
      #   address: 0.0.0.0:9020
      #   mode: tcp
      syslog_2:
        type: syslog
        address: 0.0.0.0:9021
        mode: udp
    sinks:
      my_sink_id:
        type: console
        inputs:
          - syslog_1
          - syslog_2
          - prefix-*
        target: stdout
        encoding:
          codec: json
