apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmware
  namespace: exporters
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kremers.github.io/
      chart: vmware-exporter
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: kremers
        namespace: flux
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: vmware-creds
  values:
    image:
      tag: latest
    vsphere:
      host: 10.0.0.14
      ignoressl: true
    service:
      enabled: true
    nodeSelector:
      location: home
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
      hosts:
        - vmware-metrics.k8s.nickysemenza.com
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "vmware"
  namespace: exporters
spec:
  selector:
    matchLabels:
      app: vmware-exporter
  endpoints:
    - port: http
